# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Kyunghoon Gwak <hibouaile04@gmail.com>
"""Generate README claim blocks from repository source of truth.

The generated files are intentionally small and deterministic. They give the
README a stable place to point for public claims that are easy to let drift:
version, command surface, decision enum names, provider support, test count,
benchmark metrics, and evidence-bound citation support.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable


BENCHMARK_COMMAND = "antemortem eval benchmarks/golden_cases --json"
SELF_CHECK_COMMAND = "python scripts/check_repo_consistency.py"
TEST_COLLECTION_COMMAND = "python -m pytest --collect-only -q"
PROVIDER_COMPATIBILITY_DOC = "docs/provider_compatibility.md"
ENGLISH_CLAIMS = Path("docs/generated/claims.md")
KOREAN_CLAIMS = Path("docs/generated/claims_kr.md")


@dataclass(frozen=True)
class ClaimFacts:
    package_name: str
    package_version: str
    cli_commands: tuple[str, ...]
    decision_labels: tuple[str, ...]
    providers: tuple[str, ...]
    test_count: int
    benchmark_metrics: dict[str, float]
    benchmark_totals: dict[str, int]
    evidence_bound_status: str


CommandRunner = Callable[[list[str], Path, dict[str, str]], str]


def collect_claim_facts(
    root: Path,
    *,
    collect_tests: bool = True,
    benchmark_runner: CommandRunner | None = None,
) -> ClaimFacts:
    """Collect every public README claim from source-of-truth inputs."""
    root = root.resolve()
    pyproject = _load_pyproject(root)
    _ensure_src_on_path(root)

    from antemortem.cli import app
    from antemortem.decision import DECISION_LABELS
    from antemortem.providers.factory import supported_providers

    benchmark = load_benchmark_output(root, runner=benchmark_runner)
    return ClaimFacts(
        package_name=pyproject["project"]["name"],
        package_version=pyproject["project"]["version"],
        cli_commands=extract_commands_from_typer_app(app),
        decision_labels=tuple(DECISION_LABELS),
        providers=tuple(sorted(supported_providers())),
        test_count=_collect_test_count(root) if collect_tests else 0,
        benchmark_metrics=_coerce_metric_map(benchmark.get("metrics", {})),
        benchmark_totals=_coerce_int_map(benchmark.get("totals", {})),
        evidence_bound_status=_evidence_bound_status(),
    )


def extract_commands_from_typer_app(app: Any) -> tuple[str, ...]:
    """Return Typer command names in registered CLI order."""
    commands: list[str] = []
    for info in getattr(app, "registered_commands", ()):
        if getattr(info, "callback", None) is None:
            continue
        name = info.name or info.callback.__name__.replace("_", "-")
        commands.append(name)
    if not commands:
        raise RuntimeError("no Typer commands found")
    return tuple(commands)


def load_benchmark_output(
    root: Path,
    *,
    runner: CommandRunner | None = None,
) -> dict[str, Any]:
    """Run the documented benchmark command and parse its JSON output."""
    root = root.resolve()
    command = [
        sys.executable,
        "-m",
        "antemortem.cli",
        "eval",
        "benchmarks/golden_cases",
        "--json",
    ]
    run = runner or _run_command_json
    text = run(command, root, _subprocess_env(root))
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeError("benchmark command did not return JSON") from exc
    if "metrics" not in data or not isinstance(data["metrics"], dict):
        raise RuntimeError("benchmark JSON is missing a metrics object")
    return data


def render_english_claims(facts: ClaimFacts) -> str:
    metrics = _render_metrics(facts.benchmark_metrics)
    totals = _render_totals(facts.benchmark_totals)
    providers = " / ".join(f"`{provider}`" for provider in facts.providers)
    return f"""<!-- generated by scripts/generate_readme_claims.py; do not edit by hand -->
## Generated Repository Claims

- Package: `{facts.package_name}` `{facts.package_version}`
- Commands: {_join_code(facts.cli_commands)}
- Decisions: {_join_code(facts.decision_labels)}
- Providers: {providers}; OpenAI-compatible endpoints use `--provider openai --base-url <url>`.
- Provider capability registry: `{PROVIDER_COMPATIBILITY_DOC}` and `src/antemortem/providers/capabilities.py`
- Tests collected: `{facts.test_count}` via `{TEST_COLLECTION_COMMAND}`
- Benchmark command: `{BENCHMARK_COMMAND}`
- Benchmark totals: {totals}
- Benchmark metrics: {metrics}
- Repository self-check: `{SELF_CHECK_COMMAND}`
- Evidence-bound citations: {facts.evidence_bound_status}
"""


def render_korean_claims(facts: ClaimFacts) -> str:
    metrics = _render_metrics(facts.benchmark_metrics)
    totals = _render_totals(facts.benchmark_totals)
    providers = " / ".join(f"`{provider}`" for provider in facts.providers)
    return f"""<!-- generated by scripts/generate_readme_claims.py; do not edit by hand -->
## 생성된 Repository Claim

- Package: `{facts.package_name}` `{facts.package_version}`
- Commands: {_join_code(facts.cli_commands)}
- Decisions: {_join_code(facts.decision_labels)}
- Providers: {providers}; OpenAI-compatible endpoint는 `--provider openai --base-url <url>` 경로를 사용합니다.
- Provider capability registry: `{PROVIDER_COMPATIBILITY_DOC}` and `src/antemortem/providers/capabilities.py`
- 수집된 tests: `{facts.test_count}` (`{TEST_COLLECTION_COMMAND}`)
- Benchmark command: `{BENCHMARK_COMMAND}`
- Benchmark totals: {totals}
- Benchmark metrics: {metrics}
- Repository self-check: `{SELF_CHECK_COMMAND}`
- Evidence-bound citations: {facts.evidence_bound_status}
"""


def expected_outputs(facts: ClaimFacts) -> dict[Path, str]:
    return {
        ENGLISH_CLAIMS: render_english_claims(facts),
        KOREAN_CLAIMS: render_korean_claims(facts),
    }


def write_claims(root: Path, facts: ClaimFacts) -> None:
    for rel_path, text in expected_outputs(facts).items():
        path = root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")


def check_claims(root: Path, facts: ClaimFacts) -> list[str]:
    issues: list[str] = []
    for rel_path, expected in expected_outputs(facts).items():
        path = root / rel_path
        if not path.exists():
            issues.append(f"{rel_path}: missing generated claim file")
            continue
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual != expected:
            issues.append(f"{rel_path}: generated claims are stale; run --write")
    return issues


def _load_pyproject(root: Path) -> dict[str, Any]:
    path = root / "pyproject.toml"
    if not path.exists():
        raise RuntimeError(f"pyproject.toml not found under {root}")
    return tomllib.loads(path.read_text(encoding="utf-8"))


def _collect_test_count(root: Path) -> int:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=root,
        text=True,
        capture_output=True,
        env=_subprocess_env(root),
        check=False,
    )
    if result.returncode not in (0, 5):
        raise RuntimeError(
            "pytest collection failed while computing README claims:\n"
            + result.stdout
            + result.stderr
        )
    total = 0
    for line in result.stdout.splitlines():
        if ":" not in line:
            continue
        maybe_count = line.rsplit(":", 1)[-1].strip()
        if maybe_count.isdigit():
            total += int(maybe_count)
    if total <= 0:
        raise RuntimeError("pytest collection returned no tests")
    return total


def _evidence_bound_status() -> str:
    from antemortem.cli import app
    from antemortem.commands import lint as lint_cmd
    from antemortem.schema import Classification, NewTrap

    for model in (Classification, NewTrap):
        fields = model.model_fields
        if "evidence_hash" not in fields or "evidence_snippet" not in fields:
            raise RuntimeError(f"{model.__name__} lacks evidence binding fields")
    annotations = getattr(lint_cmd.lint, "__annotations__", {})
    if "strict_evidence" not in annotations:
        raise RuntimeError("lint command lacks strict_evidence option")
    commands = set(extract_commands_from_typer_app(app))
    if "evidence" not in commands:
        raise RuntimeError("CLI lacks evidence command")
    return "`evidence_hash` and `evidence_snippet` supported; `lint --strict-evidence` and `evidence --write-missing` available."


def _run_command_json(command: list[str], cwd: Path, env: dict[str, str]) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "benchmark command failed:\n" + result.stdout + result.stderr
        )
    return result.stdout


def _subprocess_env(root: Path) -> dict[str, str]:
    env = dict(os.environ)
    env.setdefault("PYTHONUTF8", "1")
    src = str(root / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src if not existing else src + os.pathsep + existing
    return env


def _ensure_src_on_path(root: Path) -> None:
    src = str(root / "src")
    if src not in sys.path:
        sys.path.insert(0, src)


def _coerce_metric_map(raw: dict[str, Any]) -> dict[str, float]:
    if not raw:
        raise RuntimeError("benchmark metrics object is empty")
    return {str(key): float(value) for key, value in sorted(raw.items())}


def _coerce_int_map(raw: dict[str, Any]) -> dict[str, int]:
    return {str(key): int(value) for key, value in sorted(raw.items())}


def _join_code(values: tuple[str, ...]) -> str:
    if not values:
        raise RuntimeError("cannot render an empty canonical list")
    return " / ".join(f"`{value}`" for value in values)


def _render_metrics(metrics: dict[str, float]) -> str:
    return ", ".join(f"`{key}={value:.3f}`" for key, value in metrics.items())


def _render_totals(totals: dict[str, int]) -> str:
    if not totals:
        return "`none`"
    return ", ".join(f"`{key}={value}`" for key, value in totals.items())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail if generated docs are stale.")
    mode.add_argument("--write", action="store_true", help="Write generated claim docs.")
    args = parser.parse_args(argv)

    facts = collect_claim_facts(args.root)
    if args.write:
        write_claims(args.root, facts)
        print("Generated README claim blocks updated.")
        return 0

    issues = check_claims(args.root, facts)
    if issues:
        for issue in issues:
            print(issue, file=sys.stderr)
        return 1
    print("Generated README claim blocks are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
